In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Features: parametri indipendenti

Dependent variables: variabile di cui si vuole fare la previsione in funzione dei parametri indipendenti

In [ ]:
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Se ho un grande dataset, posso cancellare le righe che hanno dati mancanti

Se ho un dataset piccolo, posso sostituire i valori vuoti con la media dei valori della colonna (o mediana, max, min ecc.)

Per sicurezza, includere sul fit() tutte le colonne numeriche, anche se non si vedono valori nulli. Potrebbero esserci ma il dataset potrebbe essere troppo grande per notarli.

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Anche i valori in stringa vanno codificati in numero.

I booleani possono diventare 0 e 1

Le stringhe possono diventare numeri ma questo darebbe un ordine ad essi che potrebbe essere mal interpretati. Meglio codificarli in vettori.

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:

from sklearn.preprocessing import LabelEncoder
y = LabelEncoder().fit_transform(y)
print(y)


[0 1 0 0 1 1 0 1 0 1]


Quando fare il feature scaling? Sempre dopo aver diviso il test set dal traning set.

Il test set deve sembrare un set completamente nuovo, come dei dati nuovi dalla produzione. Se faccio lo scaling prima della suddivisione, avrò un leak di informazioni sul training set dal set di test, che nella realtà non avrei.

E' consigliato avere l'80% dei dati come training set e il 20% come test.

random_state evita di selezionare i dati in modo random, per avere un risultato sempre uguale (solo per consistenza con il corso).

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


Il feature scaling serve per evitare che dati con ordini di grandezza molto diversi non vadano a sopperire dati più piccoli, che potrebbero non essere considerati anche se importanti. Non è sempre necessario.

Normalizzazione: funziona bene se le feature seguono una distribuzione normale.

Standardizzazione: funziona bene sempre.

Si fa lo scaling su test e training separatamente. Il fit viene fatto solo sul training, e poi applicato sia a test che a traning separatamente.

Non bisogna mai applicare lo scaling alle variabili "dummy" (variabili di testo codificate in numeri).

In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])
print(X_train)
print(X_test)

NameError: ignored