In [10]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


Non è necessario fare feature scaling, gli ordini di grandezza differenti vengono assorbiti dai coefficienti del polinomio.

Non è necessario. verificare se la relazione tra i dati è lineare prima di provare questo modello. Si perde più tempo a testare la linearità tra le variabili che a produrre il modello.

Se la relazione non è lineare, semplicemente il modello avrà un'accuratezza minore che un altro modello.

La classe utilizzata per creare la regressione si preoccupa di eliminare le dummy variable dipendenti tra loro. Inoltre gestisce in automatico la selezione delle variabili indipendenti e l'eliminazione di quelle dipendenti tra di loro (seleziona le feature che hanno più importanza statisticamente)

In [14]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [20]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
delta = y_pred-y_test
delta_n = (y_pred-y_test)/y_test*100
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1), delta.reshape(len(delta),1), delta_n.reshape(len(delta_n),1) ), axis=1))

[[ 1.03e+05  1.03e+05 -2.67e+02 -2.59e-01]
 [ 1.33e+05  1.44e+05 -1.17e+04 -8.09e+00]
 [ 1.32e+05  1.46e+05 -1.37e+04 -9.36e+00]
 [ 7.20e+04  7.78e+04 -5.82e+03 -7.48e+00]
 [ 1.79e+05  1.91e+05 -1.25e+04 -6.55e+00]
 [ 1.16e+05  1.05e+05  1.12e+04  1.06e+01]
 [ 6.79e+04  8.12e+04 -1.34e+04 -1.65e+01]
 [ 9.88e+04  9.75e+04  1.31e+03  1.34e+00]
 [ 1.14e+05  1.10e+05  3.62e+03  3.28e+00]
 [ 1.68e+05  1.66e+05  1.73e+03  1.04e+00]]


In [21]:
print(regressor.predict([[1, 0, 0, 160000, 130000, 300000]]))

[181566.92]


In [22]:
print(regressor.coef_)
print(regressor.intercept_)

[ 8.66e+01 -8.73e+02  7.86e+02  7.73e-01  3.29e-02  3.66e-02]
42467.52924853204
